### ISSUE TITLE
can't get transaction history from the database

### ISSUE THREAD

**Issue by m4hdi1995** [anonanonymous/Shellnet#12]
hello,
Latest Transactions section doesn't show any information,
balance shows correct amount,
postgres@ubuntu:~$ psql -d transaction_db
psql: FATAL:  database "transaction_db" does not exist
i think i missed something when i was setting up a psql user, any thought on that?
thanks.

**Comment by anonanonymous** [comment]
You're not doing anything wrong. I haven't pushed the transaction logging code yet. It should be up soon

**Comment by m4hdi1995** [comment]
oh , ok , thanks. i have added Wallet address QR Code too, im going to add QR code scan and Payment ID Generation too.

**Comment by m4hdi1995** [comment]
I think Separate Send, Receive, Transactions, ... Tabs are also Great.
