### ISSUE TITLE
rpc auth

### ISSUE THREAD

**Issue by m4hdi1995** [anonanonymous/Shellnet#16]
hello,
it seems that the turtlecoin doesn't support rpc-user but only rpc-password, am i right?

**Comment by anonanonymous** [comment]
I'm not sure what you mean by rpc-user. The shellnet only needs the rpc-password and uri to communicate with the turtlecoin daemon.

**Comment by m4hdi1995** [comment]
@anonanonymous it seems that the turtlecoin only needs one rpc-password arg, unlike bitcoin and some cryptonote based coins which you need both rpc-user and rpc-password, i,m trying to adapt shellnet for another coin without changing the coin core code, and i need both user and password arguments in order to auth on walletd
