### ISSUE TITLE
adaptation for another Coin

### ISSUE THREAD

**Issue by m4hdi1995** [anonanonymous/Shellnet#9]
Hello ,
I have made some changes to adapt it for another cryptonote based coin called ParsiCoin , i've also changed some rpc commands to make it work with parsicoin ,
you can see changes here : https://github.com/m4hdi1995/shellnet-webwallet-go/commit/e2526ee60375af1118bd03427222cd5dbac68767
i've just followed your set up guide : 

cat user_db.sql | psql -U postgres -h 127.0.0.1 command returned :
CREATE DATABASE
You are now connected to database "users" as user "postgres".
CREATE TABLE
**************************************************************************
cat transaction_db.sql | psql -U postgres -h 127.0.0.1 returned : 
CREATE DATABASE
You are now connected to database "tx_history" as user "postgres".
CREATE TABLE
ERROR:  syntax error at or near "references"
LINE 3: addr_id references address(id),
**************************************************************************
cd services/main ; ./run.sh & disown returned :
Using default HOST_PORT - 8080 
**************************************************************************
cd services/user ; ./run.sh & disown returned : 
You connected to your database.
**************************************************************************
cd services/wallet ; ./run.sh & disown returned : 
 You connected to your database.
Using default RPC_PORT - 8070
**************************************************************************
but it seems that front end had some problems it does not work , i tried hosting on same server with LAMP , Nginx and Xampp didn't worked, i've deleted .html from all files names because it returned : The requested URL /login was not found on this server. with click on login sign up ,etc. however it just shows the web pages , login and sign up doesn't work , filled login + click on login button returns : The requested URL /{{ was not found on this server.
Thanks for your info.

**Comment by ParsiCoin** [comment]
well, problem solved, i can now open wallet on port 8080, signup doesn't work , working on it.

**Comment by m4hdi1995** [comment]
well, problem solved, i can now open wallet on port 8080, signup doesn't work , working on it.

**Comment by m4hdi1995** [comment]
signup problem related errors : (wallet/run.sh)

 http: panic serving 127.0.0.1:55506: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc00007cc80)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x6fbac0, 0xc000140600)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
main.createWallet(0x6feba0, 0x7aef40, 0xc00013a1c0, 0x7ac240)
        /root/wallet/services/wallet/wallet.go:84 +0x1fe
main.newAddress(0x7aef40, 0xc00013a1c0, 0xc00012e600, 0x0, 0x0, 0x0)
        /root/wallet/services/wallet/wallet.go:91 +0xc4
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000054400, 0x7aef40, 0xc00013a1c0, 0xc00012e600)
        /root/root/wallet/src/github.com/julienschmidt/httprouter/router.go:334 +0x792
net/http.serverHandler.ServeHTTP(0xc00006f520, 0x7aef40, 0xc00013a1c0, 0xc00012e600)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00007cc80, 0x7af1c0, 0xc0000547c0)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5

(on walletd) : 

WARNING Authorization required 127.0.0.1:33696

**Comment by m4hdi1995** [comment]
problem solved, go lang installed via package manager on ubuntu 18.04.
